main_app/urls.py
from django.urls import path
from main_app import views

urlpatterns = [
    path('prespense' , views.ListProductsAvaliable.as_view() , name = 'pro_ava'),
    path('prodcuts' , views.ListProducts.as_view() , name = 'pro'),
    path('/test' , views.Test.as_view() , name = 'test'),
    path('' , views.HomeView.as_view() , name = 'index'),
    path('categories' , views.Categories.as_view() , name = 'categories'),
    path('new_products' , views.NewProducts.as_view() , name = 'new_products'),
    path('busket_adding/' , views.busket_adding , name = 'busket_adding' ),
    path('check_out/' , views.check_out , name = 'check_out'),
    path('user/<slug:slug>' , views.DetailViewAccount.as_view() , name = 'user' ),
    path('<slug:slug>' , views.CategoriesDetail.as_view() , name = 'cat'),
    path('<slug:sluge>/<slug:slug>' , views.DetailProduct.as_view() , name = 'detail_product'),
    path('/feed_back' , views.FeedBack.as_view() , name = 'feed_back'),
]

store_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from store_project import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('main_app.urls')),
    path('' , include('user_app.urls')),
]

# urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.urls import reverse
from user_app.models import MyCustomUser

class Category(models.Model):
    category = models.CharField(max_length=225)
    photo = models.ImageField(upload_to = 'media' , null=True)
    slug = models.SlugField()
    is_active = models.BooleanField()
    date_added = models.DateTimeField(auto_now_add=True)
    time_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category
    
    def get_absolute_url(self):
        return reverse('cat' , kwargs={'slug' : self.slug})

class Product(models.Model):
    category = models.ForeignKey(Category , on_delete=models.CASCADE)
    name = models.CharField(max_length=225 , null=True)
    price = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(blank=True , null=True)
    price_with_discount = models.PositiveIntegerField(null=True , blank=True)
    is_new = models.BooleanField(null=True , blank=True)
    description = models.TextField()
    characters = models.TextField(null=True)
    short = models.CharField(max_length=225 , null = True , blank = True)
    slug = models.SlugField()
    is_prespense = models.BooleanField(null = True)
    is_active = models.BooleanField()
    date_added = models.DateTimeField(auto_now_add=True)
    time_edited = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('detail_product' , kwargs={'sluge' : self.category.slug , 'slug' : self.slug})

    def save(self , *args , **kwargs):
        if self.discount:
            self.price_with_discount = self.price - (self.discount * self.price / 100)
            super().save(*args, **kwargs)
        else:
            self.price_with_discount = self.price
            super().save(*args, **kwargs)
        

    def __str__(self):
        return self.name

class Photos(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    photot = models.ImageField(upload_to = 'media')
    is_main = models.BooleanField()
    is_active = models.BooleanField()
    date_added = models.DateTimeField(auto_now_add=True)
    time_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.name}"

class ProductInBasket(models.Model):
    order = models.ForeignKey('Order' , on_delete=models.CASCADE , null = True)
    product = models.ForeignKey(Product , on_delete=models.CASCADE , null=True)
    session_key = models.CharField(max_length=225 , null=True)
    product_total_price = models.IntegerField(null=True)
    number = models.PositiveBigIntegerField(null=True)
    discount = models.PositiveIntegerField(blank=True , null=True)
    is_active = models.BooleanField(null=True)
    date_added = models.DateTimeField(auto_now_add=True , null=True)
    time_edited = models.DateTimeField(auto_now=True , null=True)
    
    # def save(self , *args , **kwargs):
    #     products = P
    #     self.total_products_amount = int(self.product_total_price) + int(self.)
    #     super().save(*args, **kwargs)

class ProductInOrder(models.Model):
    order = models.ForeignKey('Order' , on_delete=models.CASCADE , null = True)
    product = models.ForeignKey(Product , on_delete=models.CASCADE , null=True)
    session_key = models.CharField(max_length=225 , null=True)
    product_total_price = models.IntegerField(null=True)
    number = models.PositiveBigIntegerField(null=True)
    discount = models.PositiveIntegerField(blank=True , null=True)
    is_active = models.BooleanField(null=True)
    date_added = models.DateTimeField(auto_now_add=True , null=True)
    time_edited = models.DateTimeField(auto_now=True , null=True)

    def save(self , *args , **kwargs):
        if not self.product_total_price:
            if self.discount:
                product_total_price = int(self.number) * int(self.product.price) * (self.product.discount) / 100
                super().save(*args, **kwargs)
            else:
                product_total_price = int(self.number) * int(self.product.price)
                super().save(*args, **kwargs)
            super().save(*args, **kwargs)
        else:
            super().save(*args, **kwargs)

    def __str__(self):
        return self.product.name

class ProductInFavourite(models.Model):
    session_key = models.CharField(max_length=225 , null=True)
    product_total_price = models.IntegerField(null=True)
    number = models.PositiveBigIntegerField(null=True)
    discount = models.PositiveIntegerField(blank=True , null=True)
    is_active = models.BooleanField(null=True)
    date_added = models.DateTimeField(auto_now_add=True  ,null=True)
    time_edited = models.DateTimeField(auto_now=True , null=True)

class Order(models.Model):
    status = models.ForeignKey('Status' , on_delete=models.DO_NOTHING , null=True)
    session_key = models.CharField(max_length=225 , null=True)
    user = models.ForeignKey(MyCustomUser , on_delete=models.CASCADE , null=True)
    name = models.CharField(max_length=225 , null=True)
    surname = models.CharField(max_length=225 , null=True)
    email = models.EmailField(null=True)
    adress = models.TextField(null=True)
    is_active = models.BooleanField(null=True)
    date_added = models.DateTimeField(auto_now_add=True , null=True)
    time_edited = models.DateTimeField(auto_now=True)
    total_price = models.IntegerField(null=True)

    # def save(self , *args , **Kwargs):
    #     order = Orders.ob
    #     if self.total_price == None or 0:
    #         self.total_price = self..productinorder_set.all()

    # def __str__(self):
    #     return 'замовлення'

class Status(models.Model):
    status = models.CharField(max_length=225)
    is_active = models.BooleanField()
    date_added = models.DateTimeField(auto_now_add=True , null=True)
    time_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.status

templates/account_detail_view.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal Account</title>
</head>
<style>
    .testy{
        margin-top: 120px;
    }
</style>
<body>
    <div class="container roman">
        <div class="account-box">
            <div class="accont">
                <div class="person">
                    <div class="personal_photo">
                        <img src="/static/images/aaa.png" class="pers_photo">
                    </div>
                    <div class = 'personal_inf'>
                        <h1>Hello {{user.username}}</h1>
                        <h3>Phone Number - {{user.phone}}</h3>
                        <h3>Email - {{user.email}}</h3>
                        <!-- <p href = "#">Settings</p> -->
                    </div>
                </div>
                {% for i in orders %}
                    {% if i.is_active %}
                    <div class="inner">
                        <div class="top-gun">
                            <div class="product-info">
                                {% for n in m %}
                                    {% if n.order == i %}
                                    <div class="product-item">
                                        <img src="{{ n.product.photos_set.first.photot.url }}" alt="{{ i.product.name }}" class='img-es' />
                                        <div class="product-details">
                                            <p id="kros"><b>PRODUCT -</b> {{ n }}</p>
                                            <p id="m100m" style="display: none;"><b>PRODUCT -</b> {{ n.product.short }}</p>
                                            <p><b>PRICE - </b> {{ n.product_total_price }} грн</p>
                                            <p><b>CAPACITY - </b> {{ n.product.category }}</p>
                                            <p class="hidden">{ n.product_total_price }</p>
                                        </div>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="order-summary">
                                <p style="margin: 0;"><b class="total-price">TOTAL:</b> {{ i.total_price }} грн</p>
                                <p style="margin: 0;"><b class="status">STATUS -</b> {{ i.status }}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</body>
<script>
    $(document).ready(function(){
        $(".hidden").each(function(){
                products_total_amount += parseInt($(this).text())
        })
    })
</script>
</html>


{% endblock content %}

templates/categories.html
{% extends 'base.html' %}
{% block content %}
<style>
    .img-card1{
        height: 300px !important;
        width: 300px !important;
        object-fit: cover;
    }
    @media screen and (max-width:1301px){
        .line-rr{
            right: 80px !important;
        }
        .line-ll{
            left: 80px !important;
        }
        #c5{
            display: none;
        }
    }
    @media screen and (max-width:961px){
        .line-rr{
            right: 50px !important;
        }
        .line-ll{
            left: 50px !important;
        }
    }
    .line-rr, .line-ll {
        top: 675px;
    }
    .line-rr{
        right: 209px;
    }
    .line-ll{
        left: 209px;
    }
    .card{
        height: 300px !important;
        width: 300px;
    }
    #text{
        padding: 0 auto;
        margin-top: -170px;
        text-align: center;
        font-size: 22px;
        color: rgb(255, 255, 255);
    }
    @media screen and (max-width:501px) {
        .img-card1{
        height: 250px !important;
        width: 250px !important;
        object-fit: cover;
    }
    .card{
        height: 250px !important;
        width: 250px;
    }
    #text {
    padding: 0 auto;
    margin-top: -142px;
    text-align: center;
    font-size: 22px;
    color: rgb(255, 255, 255);
    }
    }
.card a {
    display: initial;
    align-items: initial;
    justify-content: initial;
    height: initial;
    width: 100px;
    background-color: initial;
    border-radius: initial;
    border: initial;
    margin-top: initial;
    color: initial;
    font-size: initial;
    text-align: initial;
    margin-left: initial;
    margin-top: initial;
    border: initial;
    position: initial;
    bottom: initial;
    left: initial;
    text-decoration: initial;
}
/* @media screen and (max-width:1101px){
    .line-rr{
        right: 110px !important;
    }
    .line-ll{
        left: 110px !important;
    }
} */
</style>
<div class="autoplay">
    <div>
        <img src="static/images/aaaa.png"  class="bi_img">
    </div>
    <div>
        <img src="static/images/slider1.jpg"  class="bi_img">
    </div>
    <div>
        <img src="static/images/aaaa.png"  class="bi_img">
    </div>
    <div>
        <img src="static/images/slider1.jpg"  class="bi_img">
    </div>
        
</div>
<!-- <div style="width: 10px; height: 1px;" id="sts"></div> -->
<div class='line line-ll'></div>
<div class='line line-rr'></div>
<div class='main container'>
    <h3 id='h3'>CATEGORIES</h3>
</div>
<div class='card-box container'>
    <div class='cards container'>
        <div class='wraper'>
            {% for i in list %}
            <div class='test'>
                <div class='card'>
                    <div class='card-top' style='position:relative;'>
                        <a href = "{{ i.get_absolute_url }}">                        
                            <img src="{{ i.photo.url }}" alt="{{ i.product.name }}" class='img-card1'/>
                        </a>
                        <p id="text">{{ i|upper }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

templates/detail_product.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<link rel='stylesheet' href="{% static 'css/product_detail.css' %}">
<style>
    /* .fox{
        margin-top: 100px !important;
    } */
    .product-box{
        margin-top:100px
    }
    .nn{
        margin-top: 100px;
    }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $("#des").click(function(){
            $("#desc").css('display' , 'block');
            $("#char").css('display' , 'none');
            $("#deli").css('display' , 'none');
        });
        $("#cha").click(function(){
            $("#desc").css('display' , 'none');
            $("#char").css('display' , 'block');
            $("#deli").css('display' , 'none');
        });
        $("#del").click(function(){
            $("#desc").css('display' , 'none');
            $("#char").css('display' , 'none');
            $("#deli").css('display' , 'block');
        });
    });
</script>
<section>
    <div class='product-box'>
        <div class = 'container product'>
            <div class='product-left'>
                {% for i in photos %}
                    {% if i.product.is_prespense %}
                        <img src="{{ i.photot.url }}" class="seel">
                    {% else %}
                        <img style = "  filter: grayscale(100%); "src="{{ i.photot.url }}" class="seel calm">
                        <h1>NOT AVALIABLE</h1>
                    {% endif %}
                {% endfor %}
            </div>
            <div class='product-right'>
                <p id='rt'>ROUTE</p>
                <div class='route'>
                    <p><a href="{% url 'index' %}">Home</a>/<a href="{{ object.category.get_absolute_url }}">{{ object.category }}</a>/<a href="{{ object.get_absolute_url }}">{{ object.slug }}</a>/</p>
                </div>
                <h1>{{ object.name }}</h1>
                    {% if object.discount %}
                        <div class='price_plus'>
                            <p><b>DISCOUNT : </b>{{ object.discount }}%</p>
                            <div class='price_price'>
                                <p class='precedence'>{{ object.price_with_discount }}₴</p>
                                <strike class='not_precedence'>{{ object.price }}₴</strike>
                            </div>
                        </div>
                    {% else %}
                    <div class='price'>
                        <p>{{ object.price }}₴</p>
                    </div>
                    {% endif %}
                    <form class="main_form" action="{% url 'busket_adding' %}">
                        {% csrf_token %}
                        <div class='buy'>
                            <input id='number' type='number' value= 1 min=1>
                        </div>
                        <button id='needed_btn' type='submit' data-product_id = "{{ object.id }}" data-product_name="{{ object.name }}"
                        data-product_price = "{{ object.price_with_discount }}"
                        data-product_id = "{{ object.id }}">BUY</button>
                    </form>
                <div class='tab' style="display: none;">
                    <div class='tab-top'>
                        <button id='des'>Descriptions</button>
                        <button id='cha'>Charasterics</button>
                        <button id='del'>Delivery</button>
                    </div>
                    <div class='tab-bottom'>
                        <p id='desc'>{{ object.description }}</p>
                        <p id='char'>{{ object.product_characteristic}}</p>
                        <p id='deli'>{% lorem 1 b random %}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <h3 id='megan' style="color: black">YOU CAN BE ALSO INTERESTED IN</h3>
            <div class='wraper-2'>
                {% for i in products %}
                    <div class='test-2'>
                        <a href = "{{ i.get_absolute_url }}" style="text-decoration: none;
                                                                    color:black">
                            <div class='card-2'>
                                <div class='card-top-2' style='position:relative;'>
                                    <button class="fav"><img src = "static/images/sos.png"></button>
                                    {% if i.is_new and i.discount %}
                                        <p style='position:absolute;' class='h7dis'>{{i.discount}}% off</p>
                                        <p style='position:absolute;' class='h8dis'>new</p>
                                    {% elif i.discount %}
                                        <p style='position:absolute;' class='h5dis'>{{ i.discount }}% off</p>
                                    {% elif i.is_new %}
                                        <p style='position:absolute;' class='h6dis'>new</p>
                                    {% endif %}
                                    {% for n in i.photos_set.all %}
                                            {% if n.product.name == i.name %}
                                            {% if n.product.is_prespense %}
                                                <img src="{{ n.photot.url }}" alt="{{ n.product.name }}" class='img-card-2'/>
                                            {% else %}
                                                <img src="{{ n.photot.url }}" style = "  filter: grayscale(100%);" alt="{{ n.product.name }}" class='img-card-2 calm'/>
                                            {% endif %}
                                            {% endif %}
                                    {% endfor %}
                                </div>
                                <div class='card-bottom-2'>
                                    <h3 class="ukkk">{{ i.name }}</h3>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/feed_back.html
{% extends 'base.html' %}
{% block content %}
<div class="feed_back-box">
    <div class="container">
        <h1>Will be available soon</h1>
    </div>
</div>

{% endblock content %}

templates/products.html
{% extends 'base.html' %}
{% block content %}

<style>
    .line-rr , .line-ll{
        top: 675px;
    }
    .line-rr{
        right: 209px;
    }
    .line-ll{
        left: 209px;
    }
    #av{
        display: inline-block;
        padding: 10px 20px;
        background-color: #4ec67f; /* Button background color */
        color: #fff; /* Text color */
        border-radius: 5px; /* Rounded corners */
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease; /* Smooth transition on hover */
        margin: 20px; /* Add margin for spacing */
    }
    #av:hover {
        background-color: #4ec67f; /* Darker background color on hover */
    }
    #nonpe{
        text-align: right;
        margin-right: 56px;
    }
</style>
<div class="autoplay">
    <div>
        <img src="static/images/aaaa.png" class="bi_img" >
    </div>
    <div>
        <img src="static/images/slider1.jpg"  class="bi_img">
    </div>
    <div>
        <img src="static/images/aaaa.png"  class="bi_img">
    </div>
    <div>
        <img src="static/images/slider1.jpg"  class="bi_img">
    </div>
</div>
    <div class='line line-ll'></div>
    <div class='line line-rr'></div>
    <div class='main container'>
        <h3 id='h3'>PRODUCTS</h3>
    </div>
<div class="products-box">
    <div class="container">
        <div id="nonpe">
            <a id="av" href = "{% url 'pro_ava' %}">Avaliable</a>
        </div>
        <div class='wraper'>
            {% for i in list %}
                <div class='test'>
                    <div class='card'>
                        <div class='card-top' style='position:relative;'>
                            <button class="fav"><img src = "static/images/sos.png" ></button>
                            {% if i.is_new and i.discount %}
                                <p style='position:absolute;' class='h7dis'>{{i.discount}}% off</p>
                                <p style='position:absolute;' class='h8dis'>new</p>
                            {% elif i.discount %}
                                <p style='position:absolute;' class='h5dis'>{{ i.discount }}% off</p>
                            {% elif i.is_new %}
                                <p style='position:absolute;' class='h6dis'>new</p>
                            {% endif %}
                            {% for n in i.photos_set.all %}
                            {% if n.product.name == i.name %}
                            {% if n.product.is_prespense %}
                            
                            <img src="{{ n.photot.url }}" alt="{{ i.product.name }}" class='img-card' id="kik"/>
                            <a href="{{ i.get_absolute_url }}" style="display: none;" class="uno">
                                <img src="{{ n.photot.url }}" alt="{{ i.product.name }}" class='img-card'/>
                            </a>
                            <h3 class="uk">{{ n }}</h3>
                            {% else %}
                            <img style = "filter: grayscale(100%);" src="{{ n.photot.url }}" alt="{{ i.product.name }}" class='img-card calm' id="kik"/>
                            <a href="{{ i.get_absolute_url }}" style="display: none;" class="uno">
                                <img class='megan_beer img-card calm' style = "filter: grayscale(100%);" src="{{ n.photot.url }}" alt="{{ i.product.name }}" />
                            </a>
                            <h3 class="uk">{{ n }}</h3>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </div>
                        <div class='card-bottom'>

                            {% if i.discount%}
                            <div class='discount'>
                                <h4 class='h4dis'>{{i.price_with_discount}}₴</h4>
                                <h4 class='h4price'>{{i.price}}₴</h4>
                            </div>
                            {% else %}
                                <h4 class='h4realprice'>{{ i.price }}₴</h4>
                            {% endif %}

                            <h3>{{i.name}}</h3>
                            <p>{{i.description|slice:42}}...</p>
                            <a href="{{ i.get_absolute_url }}">Show</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">1</a>
                    <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                {% endif %}
        
                <span class="current">
                    {{ page_obj.number }}
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
        </div>
    </div>
    </div>
</div>

{% endblock content %}

templates/products_avaliable.html
{% extends 'base.html' %}
{% block content %}

<style>
    .line-rr , .line-ll{
        top: 680px;
    }
    .line-rr{
        right: 209px;
    }
    .line-ll{
        left: 209px;
    }
    #av{
        display: inline-block;
        padding: 10px 20px;
        background-color: #4ec67f; /* Button background color */
        color: #fff; /* Text color */
        border-radius: 5px; /* Rounded corners */
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease; /* Smooth transition on hover */
        margin: 20px; /* Add margin for spacing */
    }
    #av:hover {
        background-color: #4ec67f; /* Darker background color on hover */
    }
    #nonpe{
        text-align: right;
        margin-right: 56px;
    }
</style>
<div class="autoplay">
    <div>
        <img src="static/images/aaaa.png" class="bi_img" >
    </div>
    <div>
        <img src="static/images/slider1.jpg"  class="bi_img">
    </div>
    <div>
        <img src="static/images/aaaa.png"  class="bi_img">
    </div>
    <div>
        <img src="static/images/slider1.jpg"  class="bi_img">
    </div>
</div>
    <div class='line line-ll'></div>
    <div class='line line-rr'></div>
    <div class='main container'>
        <h3 id='h3'>PRODUCTS AVA</h3>
    </div>
<div class="products-box">
    <div class="container">
        <div id="nonpe">
            <a href = "{% url 'pro' %}" id="av">all</a>
        </div>
        <div class='wraper'>
            {% for i in ava %}
                <div class='test'>
                    <div class='card'>
                        <div class='card-top' style='position:relative;'>
                            <button class="fav"><img src = "static/images/sos.png" ></button>
                            {% if i.is_new and i.discount %}
                                <p style='position:absolute;' class='h7dis'>{{i.discount}}% off</p>
                                <p style='position:absolute;' class='h8dis'>new</p>
                            {% elif i.discount %}
                                <p style='position:absolute;' class='h5dis'>{{ i.discount }}% off</p>
                            {% elif i.is_new %}
                                <p style='position:absolute;' class='h6dis'>new</p>
                            {% endif %}
                            {% for n in i.photos_set.all %}
                            {% if n.product.name == i.name %}
                            {% if n.product.is_prespense %}
                            
                            <img src="{{ n.photot.url }}" alt="{{ i.product.name }}" class='img-card' id="kik"/>
                            <a href="{{ i.get_absolute_url }}" style="display: none;" class="uno">
                                <img src="{{ n.photot.url }}" alt="{{ i.product.name }}" class='img-card'/>
                            </a>
                            <h3 class="uk">{{ n }}</h3>
                            {% else %}
                            <img style = "filter: grayscale(100%);"src="{{ n.photot.url }}" alt="{{ i.product.name }}" class='img-card calm' id="kik"/>
                            <a href="{{ i.get_absolute_url }}" style="display: none;" class="uno">
                                <img class='megan_beer' style = "  filter: grayscale(100%);" src="{{ n.photot.url }}" alt="{{ i.product.name }}" class='img-card calm'/>
                            </a>
                            <h3 class="uk">{{ n }}</h3>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </div>
                        <div class='card-bottom'>

                            {% if i.discount%}
                            <div class='discount'>
                                <h4 class='h4dis'>{{i.price_with_discount}}₴</h4>
                                <h4 class='h4price'>{{i.price}}₴</h4>
                            </div>
                            {% else %}
                                <h4 class='h4realprice'>{{ i.price }}₴</h4>
                            {% endif %}

                            <h3>{{i.name}}</h3>
                            <p>{{i.description|slice:42}}...</p>
                            <a href="{{ i.get_absolute_url }}">Show</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">1</a>
                    <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                {% endif %}
        
                <span class="current">
                    {{ page_obj.number }}
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
        </div>
    </div>
    </div>
</div>
{% endblock content %}